### ISSUE TITLE
Missing 1903 nanoserver/wscore images

### ISSUE THREAD

**Issue by riverar** [PowerShell/PowerShell-Docker#238] opened 2019-06-29 04:42 UTC
Missing tags/images for the latest release of Windows 10, 1903. 
See: https://hub.docker.com/_/microsoft-powershell?tab=description

**Comment by TravisEz13** [comment] 2019-06-30 18:50
This is the first request we have had to add this image.

**Comment by riverar** [comment] 2019-06-30 18:53
@TravisEz13 I think most expect `:latest` to remain up to date and not need to file a request. If that's not the case, please document as such.

**Comment by TravisEz13** [comment] 2019-06-30 20:03
I file an issue for this feature request.  We have things like Dependabot to automatically file PRs for NuGet package changes.  The problem is that there is so far there have always been breaking changes.  So automating it without a human involved would just cause things to break.

I'll ask the MCR team for a feature where they open an issue on PR when an image in the MCR we depend on changes.

**Comment by TravisEz13** [comment] 2019-06-30 20:03
I opened #240  to track this work.

**Comment by TravisEz13** [comment] 2019-06-30 21:13
#239 is done to add 1903. I need a code review.  That probably won't happen until Monday unless @RDIL is online.

The changes are simple and RDIL has enough experience in the code base.

Once it is merged, I can do the release.  Updating the tag list is manual and requires two people.

**Closed** 2019-07-01 19:03 UTC
Labels: Issue-Enhancement

**Comment by TravisEz13** [comment] 2019-07-01 22:42
The images are now deployed
